name: Test job 2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'env_name'
      version:
        description: 'Commit/tag/branch'
        required: false

jobs:
  job1:
    name: test2
    runs-on: ubuntu-latest
    env:
      TEST: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
          fetch-depth: 0
      - name: echo
        run: |
          echo ${{ github.event.inputs.environment }}
          echo $TEST
          echo ${{ github.event.inputs.version }}
